### ISSUE TITLE
Portals Colors

### ISSUE THREAD

**Issue by Suburbanno** [puuuuh/ingress-map#3]
All portals are white, whether faction or neutral, making it difficult to view, both on OpenStreetMap and Google Maps.

I suggest using the orange color for the neutral portal and the other portals the colors relative to their factions
![100009100252_261923](https://user-images.githubusercontent.com/13632826/103300981-0710ac80-49df-11eb-9eff-c9e65ba814e8.jpg)
![100033000854_98036](https://user-images.githubusercontent.com/13632826/103300982-07a94300-49df-11eb-9b3a-b62991f1c316.jpg)
Thank you for your great work!

**Comment by puuuuh** [comment]
Now you can change the colors of the icons through the settings
