### ISSUE TITLE
Login connects my account to a new device

### ISSUE THREAD

**Issue by Suburbanno** [puuuuh/ingress-map#4]
Hey, thanks for your work, the way the app currently logs in, links a new device to my account and can this result in a ban on my account?

In a scenario where I open the app to look at the map and then open the game, there are 2 different devices accessing the same account, can it carry risks?

I take for example the IITC, which works in the same way as the intel stock, is there a way to simulate the login just like the IITC does?

**Comment by puuuuh** [comment]
My map uses the same api and the same login method as IITC, the only difference is the user agent. But you can be banned anyway, so its better to use an empty account.
